version: "3.6"
services:
  web:
    image: nginx:latest
    ports:
      - 10080:80
    depends_on:
      - app
    networks:
      - web_network
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src/web:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    depends_on:
      - db
    networks:
      - web_network
      - db_network
    volumes:
      - ./src/web:/var/www/html
      - ./logs/php:/var/log/php
    working_dir: /var/www/html
    environment:
      - TZ=${TZ}
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - db_network
    volumes:
      - mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MySQL_PASSWORD=${DB_PASS}
      - TZ=${TZ}
networks:
  web_network:
  db_network:
volumes:
  mysql:
